# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wRDAYCZkphspYR7dvh4Dtq0sin7pYu4A
"""

import matplotlib.pyplot as plt
import numpy as np

"""line graph"""

x=[1,2,3]
y=[4,5,6]
plt.plot(x,y)
plt.title("line graph")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.legend(["line"])
plt.show()

"""stem plot"""

x = np.linspace(0,2)
y = np.sin(2*np.pi*x)
plt.stem(x,y,use_line_collection=True,linefmt='-.')
plt.show

"""bar chart"""

x=[10,20,30,40,50]
y=[1,2,3,4,5]
plt.bar(x,y)
plt.title("bar chart")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.legend(["bar"])
plt.show()

"""plotting histrogram"""

x=[1,2,3,4,5,6,7,8,9,10]
plt.hist(x,bins=40)
plt.title("histrogram")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.legend(["histrogram"])
plt.show

"""scatter plot"""

x=[1,4,6,8,15,16,29]
y=[1,2,3,4,5,6,7]
plt.scatter(x,y)
plt.title("scatter plot")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.legend(["scatter"])
plt.show()

"""stack plot"""

x=[1,2,3,4,5]
y=[2,4,6,8,10]
z=[1,3,6,8,9]
w=[8,5,3,2,5]
plt.stackplot(x,y,z,w,colors=['r','b','g'])
plt.title("stack plot")
plt.xlabel("x-axis")
plt.ylabel("y-axis")
plt.legend(["stack"])
plt.show

"""box plot"""

np.random.seed(25)
data=np.random.normal(100,10,200)
plt.boxplot(data)
plt

"""pie chart"""

x=[1,2,3,4,5]
y=[1,2,3,4,5]
plt.pie(x,labels=y)
plt.show()

"""error plot"""

x=[1,5,3,2,6,3,5]
y=[2,5,2,6,1,6,9]
y_error=0.5
plt.errorbar(x,y)
plt

"""violin plot"""

uniform = np.arange(-100, 100)
normal = np.random.normal(size = 100)*30

fig, (ax1, ax2) = plt.subplots(nrows = 1,ncols = 2,figsize =(9, 4),sharey = True)

ax1.set_title('Uniform Distribution')
ax1.set_ylabel('Observed values')
ax1.violinplot(uniform)

ax2.set_title('Normal Distribution')
ax2.violinplot(normal)
plt.show()

"""3d plot"""

x = [1, 2, 3, 4, 5]
y = [1, 4, 9, 16, 25]
z = [1, 8, 27, 64, 125]
fig = plt.figure()
a = plt.axes(projection = '3d')
a.plot3D(z, y, x)