# -*- coding: utf-8 -*-
"""Linear Regression Single Variable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYw3rrsxnycgbC6evlXAKEpsd4jmyXte
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

"""Homeprices"""

df = pd.read_csv("/content/homeprices.csv")
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')

reg = linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

x = 3300
reg.predict([[x]])

m = reg.coef_
m

c = reg.intercept_
c

y = m*x + c
y

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,reg.predict(df[['area']]),color='blue')

"""areas"""

d = pd.read_csv("/content/areas.csv")
d

p=reg.predict(d)
p

d['prices'] = p

d.to_csv('prediction.csv',index = False)

"""canada per capita income"""

ap = pd.read_csv("/content/canada_per_capita_income.csv")
ap

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('per capita income')
plt.scatter(ap.year,ap['per capita income (US$)'],color='red',marker='+')

reg = linear_model.LinearRegression()
reg.fit(ap[['year']],ap['per capita income (US$)'])

reg.predict([[2020]])

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('per capita income')
plt.scatter(ap.year,ap['per capita income (US$)'],color='red',marker='+')
plt.plot(ap.year,reg.predict(ap[['year']]),color='blue')